# config/packages/security.yaml
security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            # Assure que les outils de dev et les assets sont toujours accessibles
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppAuthenticator
            login_throttling: true
            
            logout:
                path: app_logout
                # 🚀 REDIRECTION APRÈS DÉCONNEXION : On retourne à l'accueil
                target: app_home

            remember_me:
                secret: '%kernel.secret%' # Utilise la clé secrète de ton projet
                lifetime: 604800 # 1 semaine
                path: /
                # by default, the feature is enabled by checking a checkbox in the
                # login form, uncomment the following line to always enable it.
                #always_remember_me: true

    # Note: Seule la *première* règle qui correspond est appliquée
    access_control:
        # 🚀 PROTECTION DE L'ÉTAGÈRE : 
        # On interdit l'accès à /etagere aux personnes non connectées.
        # Ils seront automatiquement redirigés vers la page de login s'ils essaient d'y aller.
        - { path: ^/etagere, roles: ROLE_USER }
        
        - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Valeur minimale pour bcrypt
                time_cost: 3 # Valeur minimale pour argon
                memory_cost: 10 # Valeur minimale pour argon